### ISSUE TITLE
Which versions of kernel/python packages behave best with targetcli-fb and on which platform?

### ISSUE THREAD

**Issue by omac777** [agrover/targetcli-fb#55]
Hi there, 

I have recently installed targetcli-fb using the manjaro arch.
That kernel was possibly 3.18 and it was ok.
Then I did an update to kernel41 and it seemed be ok.
Another week ago, I did an update to kernel 42/kernel 43 and targetcli wasn't working anymore.
Rolling back is tricky, it involves individual package management which quickly becomes time consuming.

Oddly enough the same behaviour occurred using fedora23beta using targetcli packages from fedora repos.  Again Rolling back is time-consuming for Fedora23.

Even more odd is last week Debian Sid packages listed targetcli as part of their repo.  I installed that and then this past monday when I updated, some python packages along with the kernel were affected and targetcli wasn't working anymore.  Again rolling back is time-consuming for Debian.

From what I experienced, both targetcli/targetcli-fb seem to be fragile and vulnerable to python/kernel updates.

So here is my question:  which Linux kernel version and python packages versions produce expected well-behaving targetcli?

How can I prevent targetcli from breaking from:
apt-get update
pacman -Syu
dnf update
?

What's the preferred Linux distro for targetcli-fb?  It seems arch(manjaro) has it in their repos, but Debian Sid and Fedora 23 beta provide targetcli(non-fb), but not currently well-behaving for me.

Thank you for listening

**Comment by agrover** [comment]
Fedora uses -fb - the package is called just 'targetcli' but the version indicates it is based on targetcli-fb. I work for Red Hat so Fedora is where most of the -fb development happens, actually.

BTW targetcli is just the configuration tool for the in-kernel target code, 'LIO'. If you can configure the target ok but things don't work, blame the kernel not targetcli :smile: 

There is a reported issue with LIO in Linux kernel 4.2.x, will be fixed in 4.3, so all distros using this kernel will have the same issue. I don't know if 4.2.x will get the fix so I'd recommend 4.1 until 4.3 comes out.

w.r.t Python, targetcli-fb should work on both Python 2 or 3, and should not be affected by minor version updates. If you do see this, please definitely open an issue.
